# Generated by Django 5.1.7 on 2025-05-08 11:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discription', models.CharField(max_length=500)),
                ('job', models.CharField(choices=[('Python developer', 'pythondeveloper'), ('mearn stack', 'mearnstack'), ('digital marketing', 'digitalmarketing'), ('graphic design', 'graphicdesign')], default='python developer', max_length=200)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=200)),
                ('image', models.ImageField(default='project_pic/default', null=True, upload_to='project_pic')),
                ('link', models.CharField(max_length=300, null=True)),
                ('project_discription', models.CharField(max_length=500, null=True)),
                ('work', models.CharField(choices=[('website', 'website'), ('graphic design', 'graphic design')], default='website', max_length=200)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolios', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
